import type { Metadata } from "next";
import { EB_Garamond, Oswald, Fira_Code } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import Footer from "@/components/Footer";

type Props = {
  children: React.ReactNode;
};

const ebGaramond = EB_Garamond({
  subsets: ["latin", "vietnamese"],
  variable: "--font-eb-garamond",
  display: "swap",
});

const oswald = Oswald({
  subsets: ["latin", "vietnamese"],
  variable: "--font-oswald",
  display: "swap",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-fira-code",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ni Viện Viên Không",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className={`${ebGaramond.variable} ${oswald.variable} ${firaCode.variable}`}
    >
      <body className={`antialiased min-h-screen flex flex-col`}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
      <Footer />
    </html>
  );
}
